# main.yml
name: main branch auto ci process script

on: # 아래 job을 실행시킬 상황
  push:
    branches: [main] # main브랜치 푸쉬 받으면 작동

jobs: # 작동할 일
  deploy:
    name: deploy #github 아이콘에 나타날 과정 이름
    runs-on: self-hosted # GitHub Actions의 일부로 사용자 정의된 머신으로 self-hosted runner라 불림

    steps:
      - name: excuting remote ssh commands # 각 단계 이름
        uses: appleboy/ssh-action@v0.1.9 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_ID }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PEM }} # ec2 pem key
          port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/Cloud-Vanilla-Blog/
            git pull origin main
            npm i
            pm2 kill
            npm run build:deploy
            pm2 start npm -- run start
